export const PROVINCES = [
  "Punjab",
  "Sindh",
  "Khyber Pakhtunkhwa",
  "Balochistan",
  "Islamabad Capital Territory",
  "Gilgit-Baltistan",
  "Azad Jammu & Kashmir",
] as const;

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  Punjab: [
    "Lahore",
    "Rawalpindi",
    "Murree",
    "Wah Cantt",
    "Faisalabad",
    "Multan",
    "Gujranwala",
    "Sialkot",
    "Bahawalpur",
    "Sargodha",
    "Sahiwal",
    "Sheikhupura",
    "Jhang",
    "Rahim Yar Khan",
    "Gujrat",
    "Kasur",
    "Okara",
    "Dera Ghazi Khan",
    "Sadiqabad",
    "Chiniot",
    "Kamoke",
    "Hafizabad",
    "Mianwali",
    "Muzaffargarh",
    "Vehari",
    "Khanewal",
    "Wazirabad",
    "Attock",
    "Jhelum",
    "Chakwal",
    "Bhakkar",
    "Toba Tek Singh",
    "Nankana Sahib",
    "Layyah",
    "Pakpattan",
    "Narowal",
    "Lodhran",
  ],
  Sindh: [
    "Karachi",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Nawabshah",
    "Mirpur Khas",
    "Jacobabad",
    "Shikarpur",
    "Khairpur",
    "Dadu",
    "Thatta",
    "Badin",
    "Sanghar",
    "Tando Adam",
    "Tando Allahyar",
    "Ghotki",
    "Umerkot",
    "Kashmore",
    "Matiari",
  ],
  "Khyber Pakhtunkhwa": [
    "Peshawar",
    "Mardan",
    "Mingora (Swat)",
    "Kohat",
    "Abbottabad",
    "Dera Ismail Khan",
    "Bannu",
    "Swabi",
    "Charsadda",
    "Nowshera",
    "Mansehra",
    "Haripur",
    "Chitral",
    "Buner",
    "Karak",
    "Hangu",
    "Tank",
    "Lakki Marwat",
    "Malakand",
  ],
  Balochistan: [
    "Quetta",
    "Gwadar",
    "Turbat",
    "Khuzdar",
    "Sibi",
    "Chaman",
    "Zhob",
    "Loralai",
    "Dera Murad Jamali",
    "Hub",
    "Panjgur",
    "Kalat",
    "Mastung",
    "Nushki",
    "Pishin",
  ],
  "Islamabad Capital Territory": ["Islamabad"],
  "Gilgit-Baltistan": ["Gilgit", "Skardu", "Hunza", "Ghanche", "Astore", "Diamer", "Ghizer"],
  "Azad Jammu & Kashmir": [
    "Muzaffarabad",
    "Mirpur",
    "Rawalakot",
    "Kotli",
    "Bhimber",
    "Bagh",
    "Neelum",
  ],
};
